<?php
/**
 * @file
 * contextual_range_filter.module
 *
 * Adds to Views an option to contextually filter by range.
 * For instance, if you have a View with a float field (eg Price or Distance)
 * and have added this field as the first contextual filter, then you can filter
 * your View page like so:
 *
 *   http://yoursite.com/yourview/100--199.99
 *
 * Integer, float, string and list types are supported.
 * The OR ('+') operator is supported.
 * The negate operator ("Exclude" tick box) is supported.
 * "Glossary mode" (match on first N characters of a string) is supported.
 */

const CONTEXTUAL_RANGE_FILTER_SEPARATOR1 = '--'; // same as used for dates
const CONTEXTUAL_RANGE_FILTER_SEPARATOR2 = ':';  // alternative delimiter

/**
 * Implements hook_help().
 */
function contextual_range_filter_help($path, $arg) {
  switch ($path) {
    case 'admin/help#contextual_range_filter':
      $t = t('Configuration and usage instructions are in this <a href="@README">README</a> file.<br/>Known issues and solutions may be found on the <a href="@contextual_range_filter">Contextual Range Filter</a> project page.', array(
        '@README' => url(drupal_get_path('module', 'contextual_range_filter') . '/README.txt'),
        '@contextual_range_filter' => url('http://drupal.org/project/contextual_range_filter')));
      break;
  }
  return empty($t) ? '' : '<p>' . $t . '</p>';
}

/**
 * Implements hook_menu().
 */
function contextual_range_filter_menu() {
  $items['admin/config/content/contextual-range-filter'] = array(
    'title' => 'Contextual Range Filters',
    'description' => 'Select the contextual filters that are to be converted to contextual <em>range</em> filters.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contextual_range_filter_settings'),
    'access arguments' => array('administer contextual range filters'),
    'file' => 'contextual_range_filter.admin.inc'
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function contextual_range_filter_permission() {
  return array(
    'administer contextual range filters' => array(
      'title' => t('Administer contextual range filters'),
      'description' => t('Convert contextual filters into contextual <em>range</em> filters.'),
    )
  );
}

/**
 * Split a filter range string into an array containing "from" and "to" values.
 *
 * @param string $range, format "from--to", "from--" or "--to".
 *   A single value is also allowed. A single colon is accepted instead of --
 *
 * @return array of length 2, the 2nd value equals FALSE when no separator was found
 */
function contextual_range_filter_split($range) {
  if (is_array($range)) { // defensive programming to make sure we have a string
    $range = reset($range);
  }
  $range = trim($range);
  $from_to = explode(CONTEXTUAL_RANGE_FILTER_SEPARATOR1, $range);
  if (count($from_to) < 2) {
    $from_to = explode(CONTEXTUAL_RANGE_FILTER_SEPARATOR2, $range);
  }
  return count($from_to) == 1 ? array(reset($from_to), FALSE) : $from_to;
}

/**
 * Build a range query based on the ranges passed in.
 */
function contextual_range_filter_build_range_query($views_argument_plugin, $field = NULL) {

  if (!isset($views_argument_plugin) || $views_argument_plugin->value === FALSE) {
    return;
  }
  $real_field = $views_argument_plugin->realField;
  if (!isset($field)) {
    $field = "$views_argument_plugin->tableAlias.$real_field"; // e.g. field_datafield_price.field_price_value
  }
  $is_not = !empty($views_argument_plugin->options['not']); // from "Exclude: tickbox
  $null_check = $is_not ? "OR $field IS NULL" : '';

  // All WHERE clauses are OR-ed or AND-ed together in the same group.
  // Note: NOT (a OR b OR c) == (NOT a) AND (NOT b) AND (NOT c)
  $group = $views_argument_plugin->query->set_where_group($is_not ? 'AND' : 'OR');

  foreach ($views_argument_plugin->value as $range) {

    $placeholder = $views_argument_plugin->query->placeholder($real_field);

    list($from, $to) = contextual_range_filter_split($range);

    if ($to === FALSE) { // single value, not a range
      $operator = $is_not ? '!=' : '=';
      $views_argument_plugin->query->add_where_expression($group, "$field $operator $placeholder $null_check", array($placeholder => $range));
    }
    elseif ($from != '' && $to != '') { // from--to
      $operator = $is_not ? 'NOT BETWEEN' : 'BETWEEN';
      $placeholder_from = $placeholder;
      $placeholder_to = $views_argument_plugin->query->placeholder($real_field);
      $views_argument_plugin->query->add_where_expression($group, "$field $operator $placeholder_from AND $placeholder_to $null_check",
        array($placeholder_from => $from, $placeholder_to => $to));
    }
    elseif ($from != '') { // from--
      $operator = $is_not ? '<' : '>=';
      $views_argument_plugin->query->add_where_expression($group, "$field $operator $placeholder $null_check", array($placeholder => $from));
    }
    elseif ($to != '') { // --to
      $operator = $is_not ? '>' : '<=';
      $views_argument_plugin->query->add_where_expression($group, "$field $operator $placeholder $null_check", array($placeholder => $to));
    }
  }
}
